name: app_riego
description: A new Flutter project.

environment:
  sdk: '^3.7.0'

dependencies:
  flutter:
    sdk: flutter
  path: ^1.8.3
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  uuid: ^4.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
